- id: 'turn_on_porch_lights_at_sunset'
  alias: Turn On Porch Lights at Sunset
  description: 'Turn on the porch lights at sunset'
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: switch.porch_lights
    service: switch.turn_on
  - entity_id: switch.fireplace
    service: switch.turn_on
- id: 'turn_off_porch_lights_at_night'
  alias: Turn off porch lights at 10:30 PM
  description: 'Turn off the porch lights at 10:30 PM'
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - entity_id: switch.porch_lights
    service: switch.turn_off
  - entity_id: switch.fireplace
    service: switch.turn_off
- id: 'holiday_off'
  alias: Holiday Off
  description: 'Turn off all of the holiday lights'
  trigger:
  - at: 00:30:00
    platform: time
  condition: []
  action:
  - entity_id: switch.christmas_tree
    service: switch.turn_off
  - entity_id: switch.garland
    service: switch.turn_off
  - entity_id: switch.outdoor_christmas_lights_switch
    service: switch.turn_off
- id: intrusion detection
  alias: Intrusion Detection
  description: 'When a contact sensor detects a door/window opening, trigger the alarm script'
  trigger:
  - entity_id: group.contact_sensors
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: script.trigger_alarm_if_not_disarmed
- id: 'nightly_arm'
  alias: Nightly Arm
  description: 'Arm the alarm at 10:30 PM'
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_arm_home
- id: 'disarm_on_unlock'
  alias: Disarm on Unlock
  description: 'Disarm the alarm system when a lock is unlocked'
  trigger:
  - entity_id: lock.back_door_lock_locked
    from: locked
    to: unlocked
    platform: state
  - entity_id: lock.front_door_lock_locked
    from: locked
    to: unlocked
    platform: state
  - entity_id: lock.garage_door_lock_locked # The Schlange FE599 is not reporting its state when manually locked/unlocked :(
    from: locked
    to: unlocked
    platform: state
  action:
    entity_id: alarm_control_panel.home_alarm
    service: alarm_control_panel.alarm_disarm
