- id: 'turn_on_porch_lights_at_sunset'
  alias: Turn On Porch Lights at Sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: switch.porch_lights
    service: switch.turn_on
  - entity_id: switch.fireplace
    service: switch.turn_on
- id: 'turn_off_porch_lights_at_night'
  alias: Turn off porch lights at 10:30 PM
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - entity_id: switch.porch_lights
    service: switch.turn_off
  - entity_id: switch.fireplace
    service: switch.turn_off
- id: 'holiday_off'
  alias: Holiday Off
  description: ''
  trigger:
  - at: 00:30:00
    platform: time
  condition: []
  action:
  - entity_id: switch.christmas_tree
    service: switch.turn_off
  - entity_id: switch.garland
    service: switch.turn_off
  - entity_id: switch.outdoor_christmas_lights_switch
    service: switch.turn_off
- id: intrusion detection
  alias: Intrusion Detection
  description: ''
  trigger:
  - entity_id: binary_sensor.backdoor_contact_sensor_status
    from: 'off'
    platform: state
    to: 'on'
  action:
    service: script.trigger_alarm_if_not_disarmed
