
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include customize.yaml

lutron_caseta:
  host: !secret lutron_host
  keyfile: /home/pierce/ssl/lutron/caseta.key
  certfile: /home/pierce/ssl/lutron/caseta.crt
  ca_certs: /home/pierce/ssl/lutron/caseta-bridge.crt

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code_arm_required: false
    pending_time: 0
    delay_time: 0
    trigger_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
      trigger_time: 0
    armed_away:
      pending_time: 0
      delay_time: 0
      trigger_time: 0

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: !secret amazon_url
      include_devices:
      - "Pierce's Echo Show"
      - "Bathroom Echo"
