
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

homeassistant:
  customize: !include customize.yaml

lutron_caseta:
  host: !secret lutron_host
  keyfile: /home/pierce/ssl/lutron/caseta.key
  certfile: /home/pierce/ssl/lutron/caseta.crt
  ca_certs: /home/pierce/ssl/lutron/caseta-bridge.crt

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code_arm_required: false
    pending_time: 0
    delay_time: 0
    trigger_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
      trigger_time: 0
    armed_away:
      pending_time: 0
      delay_time: 0
      trigger_time: 0

alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: !secret amazon_url
      include_devices:
      - "Pierce's Echo Show"
      - "Bathroom Echo"

speedtestdotnet:
  server_id: 14734
  scan_interval:
    minutes: 30
  monitored_conditions:
      - ping
      - download
      - upload

sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: disk_use
        arg: '/'
      - type: disk_free
        arg: '/'
      - type: disk_use_percent
        arg: '/'
      - type: last_boot
      - type: network_in
        arg: 'wlp39s0'
      - type: network_out
        arg: 'wlp39s0'
      - type: throughput_network_in
        arg: 'wlp39s0'
      - type: throughput_network_out
        arg: 'wlp39s0'
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
